"""empty message

Revision ID: 20eead10f999
Revises: 
Create Date: 2023-10-20 17:02:54.821180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eead10f999'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('code')
        batch_op.drop_column('pid')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pid', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
